### ISSUE TITLE
items not charging in the solar panel

### ISSUE THREAD

**Issue by MasterSloth1** [BedrockLegends-Mods/WoodenUtilities#14]
in version 1.0.2 when you place an item into the charge slot of the wooden solar panel it would eat your power but charge nothing.
in version 1.0.3 when you place an item into the charge slot nothing at all happens
ive tryed 
@buildinggadgets
@mekanism
@rftoolspower

QUESTION?????
also at peak generation the solar panel produces 15 rf in the config the default transfer limit of the solar panel is 10 rf, any reason for this or just an oversight or other???

**Comment by lazynessmind** [comment]
> in version 1.0.2 when you place an item into the charge slot of the wooden solar panel it would eat your power but charge nothing.
in version 1.0.3 when you place an item into the charge slot nothing at all happens
ive tryed

Gonna take look into it.

> also at peak generation the solar panel produces 15 rf in the config the default transfer limit of the solar panel is 10 rf, any reason for this or just an oversight or other???

The max output will always be 15. 

**For now you can only change:**

- [X] the interval between transfering and charging power;
- [X] the output value.
