### ISSUE TITLE
[1.16.4] dupe bug/deletion bug and right click bug

### ISSUE THREAD

**Issue by MasterSloth1** [BedrockLegends-Mods/WoodenUtilities#17]
woodenutilities-1.0.4-1.16.3
forge-35.0.7

DUPE
1. have items in bag
2. open bag gui
3. remove items
4. move bag to a different slot in your inventory
5. close bag gui
6. open bag gui to see all the original items still there

DELETE
1. have nothing in bag
2. open bag gui
3. add items in
4. move bag to a different slot in inventory
5. close bag gui
6. notice all your stuffs is gone :cry:

**Comment by lazynessmind** [comment]
Hmm. So, when the bag is moved from one slot to another the data freaks out... Working on it :+1:

**Comment by lazynessmind** [comment]
35.0.7 is 1.16.4, on 34.1.x the bug don't exist, or I can't reproduce it.

**Comment by MasterSloth1** [comment]
oops sorry lol yea MC 1.16.4

**Comment by TheSnowyChickens** [comment]
Hello,
some additional informations about the backpack:

- shift clicking items in the backpack work only for the filled slots in the picture below:
![grafik](https://user-images.githubusercontent.com/29357962/98748275-9a533b80-23b9-11eb-8a1d-4d8242f7264d.png)

- sometimes I can shift click items from the hotbar in the backpack and sometimes not

I didn't wanted to open a new issue, because this is related to the backpack, I hope it is okay. :D

Forge: 35.0.14
WU: 1.0.5
MC: 1.16.4

**Comment by BedrockLegends** [comment]
Yeah @TheSnowyChickens no worries, We will look at and get it fixed soon

**Comment by lazynessmind** [comment]
@TheSnowyChickens your bug is fixed.
@MasterSloth1 your bug is fixed too.

You both let me know if something isn't working correctly pls.

**Comment by TheSnowyChickens** [comment]
Nice, ty. 👍

**Comment by TheSnowyChickens** [comment]
Okay, found something new: @lazynessmind 

- new backpack picked from the creative menu
-> I have the backpack in the first slot
-> I open the backpack
-> I close the backpack
-> I open the backpack
-> aaaannnnd it's gone

![grafik](https://user-images.githubusercontent.com/29357962/98888049-6d755600-2497-11eb-9245-a931203c72b8.png)

I can't right click him again (with inventory closed), I need to reconnect or right click the slot first.
Forge: 35.0.15
WU: 1.0.6

Oh and there is more:
In vanilla, you can take a item and shift - double click with it on other items to put them all (same item type) in the next inventory.
-> I can't do that with your backpack, not in and not out of the backpack

**Comment by lazynessmind** [comment]
> In vanilla, you can take a item and shift - double click with it on other items, so put them all (same item type) in the next inventory.
> -> I can't do that with your backpack, not in and not out of the backpack

Thanks for letting me know
