### ISSUE TITLE
License

### ISSUE THREAD

**Issue by piisawheel** [BedrockLegends-Mods/WoodenUtilities#31]
Without a public license file, the code here is pretty much read only.  People don't technically have the right to run the software.  I don't believe that is your intent.  Can you let us know under which license you are releasing your mod under so that the community can act accordingly?

**Comment by ModernGamingWorld** [comment]
@piisawheel I have to make sure that the Developers working on the mod are still on agreement with what type of License, I have not listed one cause the mod was being rewritten

**Comment by ModernGamingWorld** [comment]
https://github.com/BedrockLegends-Mods/WoodenUtilities/commit/fad04abb488a72f7f24264bebf932447db2fbf0c
